[package]
name = "parolassh"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "parolassh_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ssh-key = { version = "0.6.7", features = ["ed25519", "rsa", "ecdsa", "dsa", "encryption", "std", "p256", "p384", "p521", "getrandom"] }
zeroize = "1.9.0"
dirs = "6.0.0"
thiserror = "2.0.19"
rand_core = { version = "0.6", features = ["getrandom"] }
russh = { version = "0.62.4", default-features = false, features = ["flate2", "ring"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "net", "time", "io-util", "macros", "sync"] }
futures-util = { version = "0.3.33", default-features = false, features = ["std", "async-await"] }

[dev-dependencies]
dirs = "6.0.0"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
zeroize = "1.9.0"

