import type { SshHost } from "./types";

const hoursAgo = (hours: number) =>
  new Date(Date.now() - hours * 3_600_000).toISOString();

/**
 * Placeholder data so the layout is reviewable before the Rust SSH backend
 * exists. Replace with a Tauri command once connections are persisted.
 */
export const sampleHosts: SshHost[] = [
  {
    id: "h-01",
    label: "Web Prod 01",
    hostname: "web01.prod.internal",
    port: 22,
    username: "deploy",
    authMethod: "publickey",
    group: "Production",
    tags: ["nginx", "web"],
    lastConnected: hoursAgo(2),
    status: "online",
  },
  {
    id: "h-02",
    label: "Web Prod 02",
    hostname: "web02.prod.internal",
    port: 22,
    username: "deploy",
    authMethod: "publickey",
    group: "Production",
    tags: ["nginx", "web"],
    lastConnected: hoursAgo(26),
    status: "online",
  },
  {
    id: "h-03",
    label: "Postgres Primary",
    hostname: "db-primary.prod.internal",
    port: 2222,
    username: "dbadmin",
    authMethod: "agent",
    group: "Production",
    tags: ["postgres", "database", "critical"],
    lastConnected: hoursAgo(0.3),
    status: "online",
  },
  {
    id: "h-04",
    label: "Postgres Replica",
    hostname: "db-replica.prod.internal",
    port: 2222,
    username: "dbadmin",
    authMethod: "agent",
    group: "Production",
    tags: ["postgres", "database"],
    lastConnected: hoursAgo(72),
    status: "offline",
  },
  {
    id: "h-05",
    label: "Staging App",
    hostname: "app.staging.internal",
    port: 22,
    username: "ubuntu",
    authMethod: "publickey",
    group: "Staging",
    tags: ["app"],
    lastConnected: hoursAgo(9),
    status: "online",
  },
  {
    id: "h-06",
    label: "Staging Worker",
    hostname: "worker.staging.internal",
    port: 22,
    username: "ubuntu",
    authMethod: "publickey",
    group: "Staging",
    tags: ["queue", "worker"],
    lastConnected: hoursAgo(48),
    status: "unknown",
  },
  {
    id: "h-07",
    label: "Build Runner",
    hostname: "ci-runner-1.build.internal",
    port: 22,
    username: "ci",
    authMethod: "publickey",
    group: "CI",
    tags: ["ci", "docker"],
    lastConnected: hoursAgo(5),
    status: "online",
  },
  {
    id: "h-08",
    label: "Edge Gateway",
    hostname: "203.0.113.24",
    port: 22022,
    username: "root",
    authMethod: "password",
    group: "Networking",
    tags: ["firewall", "critical"],
    lastConnected: hoursAgo(200),
    status: "offline",
  },
  {
    id: "h-09",
    label: "Home NAS",
    hostname: "nas.lan",
    port: 22,
    username: "pheeleep",
    authMethod: "publickey",
    group: "Personal",
    tags: ["storage", "backup"],
    lastConnected: hoursAgo(15),
    status: "online",
  },
  {
    id: "h-10",
    label: "Raspberry Pi",
    hostname: "pi.lan",
    port: 22,
    username: "pi",
    authMethod: "password",
    group: "Personal",
    tags: ["iot"],
    lastConnected: null,
    status: "unknown",
  },
  {
    id: "h-11",
    label: "Monitoring",
    hostname: "grafana.ops.internal",
    port: 22,
    username: "ops",
    authMethod: "agent",
    group: "Ops",
    tags: ["grafana", "metrics"],
    lastConnected: hoursAgo(30),
    status: "online",
  },
  {
    id: "h-12",
    label: "Log Aggregator",
    hostname: "loki.ops.internal",
    port: 22,
    username: "ops",
    authMethod: "agent",
    group: "Ops",
    tags: ["logs"],
    lastConnected: hoursAgo(120),
    status: "offline",
  },
];
