//! End-to-end audit tests against fixture SSH directories.
//!
//! Everything runs against a tempdir rather than the real `~/.ssh`, so these
//! pass on any machine. Permission-specific assertions are gated to Unix;
//! the parsing and rule-selection assertions run everywhere.

use std::collections::HashSet;
use std::fs;
use std::path::Path;

use parolassh_lib::ssh::audit::{self, AuditReport, Severity};
use parolassh_lib::ssh::generate::{self, GenerateRequest};
use parolassh_lib::ssh::keys::{self, KdfInfo, KeyFormat, PassphraseNeed};

/// A real, unencrypted Ed25519 key generated by `ssh-keygen` solely for these
/// tests. It authenticates nothing and is not used anywhere.
const ED25519_KEY: &str = "\
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACD5UW+v/KH6FctxXzdfMyNkAkxNw1T5tM2vdR5iD7wd5QAAAKBpYb5MaWG+
TAAAAAtzc2gtZWQyNTUxOQAAACD5UW+v/KH6FctxXzdfMyNkAkxNw1T5tM2vdR5iD7wd5Q
AAAEAnk0+CBdQp7KOahMmeNh1+rVQkAc0sTb56Dz6/YRvnOvlRb6/8ofoVy3FfN18zI2QC
TE3DVPm0za91HmIPvB3lAAAAFnRlc3RAcGFyb2xhc3NoLmludmFsaWQBAgMEBQYH
-----END OPENSSH PRIVATE KEY-----
";

const ED25519_PUB: &str = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPlRb6/8ofoVy3FfN18zI2QCTE3DVPm0za91HmIPvB3l test@parolassh.invalid\n";

/// A legacy PEM key using the old MD5-based encryption.
const LEGACY_PEM_KEY: &str = "\
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,7B1D5E9C4A3F2081

nOtRealKeyMaterialJustEnoughToLookLikeAPemBodyForTheAuditToClassify==
-----END RSA PRIVATE KEY-----
";

const KNOWN_HOSTS: &str = "\
github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
legacy.example.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQAB
";

const RISKY_CONFIG: &str = "\
Host bastion
    User jump
    StrictHostKeyChecking no

Host *
    ForwardAgent yes
    UserKnownHostsFile /dev/null
    IdentityFile ~/.ssh/id_ed25519
";

fn write(path: &Path, contents: &str) {
    fs::write(path, contents).expect("fixture write");
}

#[cfg(unix)]
fn chmod(path: &Path, mode: u32) {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(mode)).expect("chmod");
}

fn run(dir: &Path) -> AuditReport {
    audit::run(dir, &HashSet::new()).expect("audit runs")
}

fn rules(report: &AuditReport) -> Vec<&str> {
    report
        .findings
        .iter()
        .map(|finding| finding.rule_id.as_str())
        .collect()
}

fn severity_of(report: &AuditReport, rule_id: &str) -> Option<Severity> {
    report
        .findings
        .iter()
        .find(|finding| finding.rule_id == rule_id)
        .map(|finding| finding.severity)
}

// ------------------------------------------------------------- clean fixture

#[test]
fn a_locked_down_directory_scores_well() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    write(&dir.join("id_ed25519.pub"), ED25519_PUB);

    #[cfg(unix)]
    {
        chmod(dir, 0o700);
        chmod(&dir.join("id_ed25519"), 0o600);
    }

    let report = run(dir);
    let found = rules(&report);

    assert_eq!(report.key_count, 1);
    assert!(
        !found.contains(&"perm.key.exposed"),
        "a 0600 key must not be reported as exposed: {found:?}"
    );
    assert!(!found.contains(&"perm.dir"));
    assert!(!found.contains(&"algo.dsa"));

    // The key genuinely has no passphrase, so that finding is expected —
    // and it is the only thing costing points.
    assert!(found.contains(&"key.unencrypted"));
    assert_eq!(report.counts.critical, 0);
    assert_eq!(report.counts.high, 0);
}

// ------------------------------------------------------- permission fixtures

#[cfg(unix)]
#[test]
fn a_world_readable_key_is_critical() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    chmod(dir, 0o700);
    chmod(&dir.join("id_ed25519"), 0o644);

    let report = run(dir);

    assert_eq!(
        severity_of(&report, "perm.key.exposed"),
        Some(Severity::Critical)
    );
    assert!(report.counts.critical >= 1);
    assert!(report.score < 80, "score was {}", report.score);
}

#[cfg(unix)]
#[test]
fn a_group_readable_key_still_counts_as_exposed() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    chmod(dir, 0o700);
    // 0640 leaks to the group even though "others" cannot read it.
    chmod(&dir.join("id_ed25519"), 0o640);

    let report = run(dir);
    assert!(rules(&report).contains(&"perm.key.exposed"));
}

#[cfg(unix)]
#[test]
fn an_open_directory_and_writable_authorized_keys_are_flagged() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("authorized_keys"), ED25519_PUB);
    chmod(dir, 0o755);
    chmod(&dir.join("authorized_keys"), 0o666);

    let report = run(dir);
    let found = rules(&report);

    assert!(found.contains(&"perm.dir"));
    assert_eq!(severity_of(&report, "perm.dir"), Some(Severity::High));
    assert_eq!(
        severity_of(&report, "perm.authorized-keys"),
        Some(Severity::Critical)
    );
}

#[cfg(unix)]
#[test]
fn a_readable_but_not_writable_config_is_not_flagged() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("config"), "Host a\n  User me\n");
    chmod(dir, 0o700);
    // 0644 is readable by others but not writable — ssh accepts this.
    chmod(&dir.join("config"), 0o644);

    let report = run(dir);
    assert!(!rules(&report).contains(&"perm.config-writable"));
}

// --------------------------------------------------------- format and hygiene

#[test]
fn legacy_pem_encryption_is_reported() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_rsa"), LEGACY_PEM_KEY);
    #[cfg(unix)]
    {
        chmod(dir, 0o700);
        chmod(&dir.join("id_rsa"), 0o600);
    }

    let report = run(dir);

    assert_eq!(
        severity_of(&report, "fmt.legacy-pem-md5"),
        Some(Severity::High)
    );
    // It is encrypted, so it must not also be reported as passphrase-less.
    assert!(!rules(&report).contains(&"key.unencrypted"));
}

#[test]
fn stray_backup_copies_are_reported() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    write(&dir.join("id_ed25519.bak"), ED25519_KEY);
    #[cfg(unix)]
    {
        chmod(dir, 0o700);
        chmod(&dir.join("id_ed25519"), 0o600);
        chmod(&dir.join("id_ed25519.bak"), 0o600);
    }

    let report = run(dir);
    let found = rules(&report);

    assert!(found.contains(&"file.stray-secret"));
    // Same key in two files — the duplicate rule should catch it too.
    assert!(found.contains(&"key.duplicate"));
}

#[test]
fn orphan_public_keys_are_reported_and_paired_ones_are_not() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    write(&dir.join("id_ed25519.pub"), ED25519_PUB);
    write(&dir.join("orphan.pub"), ED25519_PUB);

    let report = run(dir);
    let orphans: Vec<&str> = report
        .findings
        .iter()
        .filter(|finding| finding.rule_id == "key.orphan-public")
        .map(|finding| finding.location.as_str())
        .collect();

    assert_eq!(orphans, vec!["orphan.pub"]);
}

#[test]
fn non_key_files_are_ignored() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("config"), "Host a\n  User me\n");
    write(&dir.join("known_hosts"), KNOWN_HOSTS);
    write(&dir.join("environment"), "FOO=bar\n");
    write(&dir.join("notes.txt"), "just a note\n");

    let report = run(dir);
    assert_eq!(report.key_count, 0, "nothing here is a private key");
}

// -------------------------------------------------------------------- config

#[test]
fn risky_config_directives_are_reported_with_line_numbers() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("config"), RISKY_CONFIG);

    let report = run(dir);
    let found = rules(&report);

    assert!(found.contains(&"cfg.strict-host-key-checking-off"));
    assert!(found.contains(&"cfg.known-hosts-devnull"));
    assert!(found.contains(&"cfg.forward-agent"));
    assert!(found.contains(&"cfg.wildcard-identity"));

    // ForwardAgent under `Host *` is worse than under a named host.
    assert_eq!(
        severity_of(&report, "cfg.forward-agent"),
        Some(Severity::High)
    );

    let strict = report
        .findings
        .iter()
        .find(|finding| finding.rule_id == "cfg.strict-host-key-checking-off")
        .unwrap();
    assert_eq!(strict.location, "config:3");
}

#[test]
fn forward_agent_on_a_named_host_is_only_medium() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(
        &dir.join("config"),
        "Host bastion\n    ForwardAgent yes\n",
    );

    let report = run(dir);
    assert_eq!(
        severity_of(&report, "cfg.forward-agent"),
        Some(Severity::Medium)
    );
}

#[test]
fn a_clean_config_produces_no_config_findings() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(
        &dir.join("config"),
        "Host prod\n  User deploy\n  IdentityFile ~/.ssh/id_ed25519\n  IdentitiesOnly yes\n",
    );

    let report = run(dir);
    let found = rules(&report);
    assert!(
        !found.iter().any(|rule| rule.starts_with("cfg.")),
        "unexpected config findings: {found:?}"
    );
}

// --------------------------------------------------------------- known_hosts

#[test]
fn unhashed_and_deprecated_known_hosts_are_reported() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("known_hosts"), KNOWN_HOSTS);

    let report = run(dir);
    let found = rules(&report);

    assert!(found.contains(&"kh.unhashed"));
    assert!(found.contains(&"kh.deprecated-algo"));
    assert_eq!(severity_of(&report, "kh.unhashed"), Some(Severity::Low));
}

// -------------------------------------------------------------- suppressions

#[test]
fn suppressed_findings_stop_costing_points() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    #[cfg(unix)]
    {
        chmod(dir, 0o700);
        chmod(&dir.join("id_ed25519"), 0o600);
    }

    let before = run(dir);
    let unencrypted = before
        .findings
        .iter()
        .find(|finding| finding.rule_id == "key.unencrypted")
        .expect("the fixture key has no passphrase");
    assert!(!unencrypted.suppressed);

    let suppressed: HashSet<String> = [unencrypted.id.clone()].into_iter().collect();
    let after = audit::run(dir, &suppressed).unwrap();

    let same = after
        .findings
        .iter()
        .find(|finding| finding.rule_id == "key.unencrypted")
        .unwrap();

    // Still listed, but no longer counted or scored against.
    assert!(same.suppressed);
    assert_eq!(after.counts.medium, before.counts.medium - 1);
    assert!(after.score > before.score);
}

#[test]
fn finding_ids_are_stable_across_runs() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);

    let first: Vec<String> = run(dir).findings.into_iter().map(|f| f.id).collect();
    let second: Vec<String> = run(dir).findings.into_iter().map(|f| f.id).collect();

    // Suppressions key off these ids, so instability would silently un-dismiss
    // findings the user has already dealt with.
    assert_eq!(first, second);
    assert!(!first.is_empty());
}

// ---------------------------------------------------------------- generation

#[test]
fn generates_an_ed25519_key_that_the_audit_accepts() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    let outcome = generate::generate(
        dir,
        GenerateRequest {
            algorithm: "ed25519".into(),
            bits: None,
            file_name: "id_ed25519".into(),
            comment: Some("me@laptop".into()),
            passphrase: Some("correct horse battery staple".into()),
            overwrite: false,
        },
    )
    .expect("generation succeeds");

    assert_eq!(outcome.key.algorithm, "Ed25519");
    assert_eq!(outcome.key.bits, Some(256));
    assert!(outcome.key.encrypted);
    assert_eq!(outcome.key.format, KeyFormat::OpenSsh);
    assert_eq!(outcome.key.comment.as_deref(), Some("me@laptop"));
    assert!(outcome.public_key_openssh.starts_with("ssh-ed25519 "));
    assert!(matches!(outcome.key.kdf, KdfInfo::Bcrypt { .. }));

    assert!(dir.join("id_ed25519").is_file());
    assert!(dir.join("id_ed25519.pub").is_file());

    // A key we just created must not immediately trip the audit.
    #[cfg(unix)]
    chmod(dir, 0o700);

    let report = run(dir);
    let found = rules(&report);
    assert!(!found.contains(&"perm.key.exposed"), "{found:?}");
    assert!(!found.contains(&"key.unencrypted"), "{found:?}");
    assert_eq!(report.counts.critical, 0);
}

#[cfg(unix)]
#[test]
fn a_generated_key_is_never_world_readable() {
    use std::os::unix::fs::PermissionsExt;

    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    generate::generate(
        dir,
        GenerateRequest {
            algorithm: "ed25519".into(),
            bits: None,
            file_name: "id_ed25519".into(),
            comment: None,
            passphrase: None,
            overwrite: false,
        },
    )
    .unwrap();

    let mode = fs::metadata(dir.join("id_ed25519"))
        .unwrap()
        .permissions()
        .mode()
        & 0o777;
    assert_eq!(mode, 0o600, "got {mode:o}");
}

#[test]
fn generation_refuses_to_clobber_an_existing_key() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);

    let request = || GenerateRequest {
        algorithm: "ed25519".into(),
        bits: None,
        file_name: "id_ed25519".into(),
        comment: None,
        passphrase: None,
        overwrite: false,
    };

    let error = generate::generate(dir, request()).unwrap_err();
    assert!(
        error.to_string().contains("already exists"),
        "got: {error}"
    );

    // The original must be untouched.
    assert_eq!(fs::read_to_string(dir.join("id_ed25519")).unwrap(), ED25519_KEY);

    // Explicit opt-in replaces it.
    let overwritten = generate::generate(
        dir,
        GenerateRequest {
            overwrite: true,
            ..request()
        },
    )
    .unwrap();
    assert!(overwritten.key.fingerprint.is_some());
}

#[test]
fn generation_rejects_names_that_escape_the_directory() {
    let temp = tempfile::tempdir().unwrap();
    let outside = temp.path().join("outside");
    let dir = temp.path().join("ssh");
    fs::create_dir_all(&outside).unwrap();
    fs::create_dir_all(&dir).unwrap();

    let error = generate::generate(
        &dir,
        GenerateRequest {
            algorithm: "ed25519".into(),
            bits: None,
            file_name: "../outside/stolen".into(),
            comment: None,
            passphrase: None,
            overwrite: false,
        },
    )
    .unwrap_err();

    assert!(error.to_string().contains("path separator"), "got: {error}");
    assert!(!outside.join("stolen").exists());
}

#[test]
fn generated_rsa_honours_the_requested_size() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    // 2048 rather than 4096 purely to keep the test fast; the point is that
    // the requested size is respected instead of ssh-key's hardcoded default.
    let outcome = generate::generate(
        dir,
        GenerateRequest {
            algorithm: "rsa".into(),
            bits: Some(2048),
            file_name: "id_rsa".into(),
            comment: None,
            passphrase: None,
            overwrite: false,
        },
    )
    .expect("rsa generation succeeds");

    assert_eq!(outcome.key.bits, Some(2048));
    assert_eq!(outcome.key.algorithm, "RSA 2048");

    // And the audit should then nudge toward 3072+.
    let report = run(dir);
    assert_eq!(
        severity_of(&report, "algo.rsa-weak"),
        Some(Severity::Medium)
    );
}

#[test]
fn generation_refuses_rsa_below_the_ssh_minimum() {
    let temp = tempfile::tempdir().unwrap();

    let error = generate::generate(
        temp.path(),
        GenerateRequest {
            algorithm: "rsa".into(),
            bits: Some(1024),
            file_name: "weak".into(),
            comment: None,
            passphrase: None,
            overwrite: false,
        },
    )
    .unwrap_err();

    assert!(error.to_string().contains("2048"), "got: {error}");
    assert!(!temp.path().join("weak").exists());
}

#[test]
fn a_passphrase_can_be_verified_without_being_stored() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    generate::generate(
        dir,
        GenerateRequest {
            algorithm: "ed25519".into(),
            bits: None,
            file_name: "id_ed25519".into(),
            comment: None,
            passphrase: Some("hunter2".into()),
            overwrite: false,
        },
    )
    .unwrap();

    let path = dir.join("id_ed25519");
    assert!(generate::verify_passphrase(&path, "hunter2").unwrap());
    assert!(!generate::verify_passphrase(&path, "wrong").unwrap());
}

// --------------------------------------------------- what connecting must ask

#[test]
fn an_unencrypted_key_is_not_worth_prompting_for() {
    let temp = tempfile::tempdir().unwrap();
    let path = temp.path().join("id_ed25519");
    fs::write(&path, ED25519_KEY).unwrap();

    assert_eq!(keys::passphrase_need(&path), PassphraseNeed::NotNeeded);
}

#[test]
fn an_encrypted_key_is_prompted_for() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    generate::generate(
        dir,
        GenerateRequest {
            algorithm: "ed25519".into(),
            bits: None,
            file_name: "locked".into(),
            comment: None,
            passphrase: Some("hunter2".into()),
            overwrite: false,
        },
    )
    .unwrap();

    assert_eq!(
        keys::passphrase_need(&dir.join("locked")),
        PassphraseNeed::Required
    );
}

#[test]
fn a_legacy_encrypted_pem_is_prompted_for() {
    let temp = tempfile::tempdir().unwrap();
    let path = temp.path().join("id_rsa");
    fs::write(&path, LEGACY_PEM_KEY).unwrap();

    assert_eq!(keys::passphrase_need(&path), PassphraseNeed::Required);
}

#[test]
fn an_unreadable_path_asks_rather_than_assuming_it_is_open() {
    let temp = tempfile::tempdir().unwrap();

    // Missing, and a file that is not a key at all: neither is evidence that
    // nothing needs to be typed, so both must land on "ask".
    let missing = temp.path().join("nowhere");
    assert!(matches!(
        keys::passphrase_need(&missing),
        PassphraseNeed::Unknown { .. }
    ));

    let junk = temp.path().join("notes.txt");
    fs::write(&junk, "this is not a private key").unwrap();
    assert!(matches!(
        keys::passphrase_need(&junk),
        PassphraseNeed::Unknown { .. }
    ));
}

// -------------------------------------------------------------------- basics

#[test]
fn a_missing_directory_is_reported_rather_than_failing() {
    let temp = tempfile::tempdir().unwrap();
    let missing = temp.path().join("no-ssh-here");

    let report = run(&missing);

    assert!(!report.dir_exists);
    assert!(report.findings.is_empty());
    assert_eq!(report.score, 100);
}

#[cfg(unix)]
#[test]
fn the_score_floors_at_zero() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    // Several *distinct* critical rules, which is what actually saturates the
    // scale now that repeats of one rule have diminishing returns.
    write(&dir.join("id_rsa"), LEGACY_PEM_KEY);
    write(&dir.join("authorized_keys"), ED25519_PUB);
    write(&dir.join("config"), "Host *\n  StrictHostKeyChecking no\n");
    chmod(dir, 0o777);
    chmod(&dir.join("id_rsa"), 0o666);
    chmod(&dir.join("authorized_keys"), 0o666);
    chmod(&dir.join("config"), 0o666);

    let report = run(dir);
    assert_eq!(report.score, 0);
}

#[test]
fn repeats_of_one_rule_do_not_saturate_the_score() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    // Ten passphrase-less keys is one decision to revisit, not ten problems.
    // Charging full weight for each would drive any real directory to 0 and
    // make the score useless for telling "untidy" from "compromised".
    for index in 0..10 {
        let path = dir.join(format!("id_ed25519_{index}"));
        write(&path, ED25519_KEY);
        // Lock each one down, otherwise the default umask makes these 0644 and
        // the test measures the permission rule instead of the one it targets.
        #[cfg(unix)]
        chmod(&path, 0o600);
    }
    #[cfg(unix)]
    chmod(dir, 0o700);

    let report = run(dir);

    // Every instance is still reported and counted...
    assert_eq!(report.counts.medium, 10);
    // ...but the score stays informative rather than bottoming out.
    assert!(
        report.score >= 80,
        "ten instances of one medium rule should not tank the score; got {}",
        report.score
    );
}

#[test]
fn distinct_rules_cost_more_than_repeats_of_one() {
    let one_rule = tempfile::tempdir().unwrap();
    for index in 0..3 {
        let path = one_rule.path().join(format!("id_ed25519_{index}"));
        write(&path, ED25519_KEY);
        #[cfg(unix)]
        chmod(&path, 0o600);
    }

    let mixed = tempfile::tempdir().unwrap();
    let key = mixed.path().join("id_ed25519");
    write(&key, ED25519_KEY);
    #[cfg(unix)]
    chmod(&key, 0o600);
    write(&mixed.path().join("known_hosts"), KNOWN_HOSTS);
    write(
        &mixed.path().join("config"),
        "Host *\n  ForwardAgent yes\n  StrictHostKeyChecking no\n",
    );

    #[cfg(unix)]
    {
        chmod(one_rule.path(), 0o700);
        chmod(mixed.path(), 0o700);
    }

    assert!(
        run(mixed.path()).score < run(one_rule.path()).score,
        "a directory with several different problems should score worse"
    );
}

// ------------------------------------------------------------- smoke test

/// Audit the real `~/.ssh`, if there is one.
///
/// Ignored by default so the suite stays hermetic — run it with
/// `cargo test -- --ignored` to check the scanner against a directory that
/// was not built by these fixtures. Prints rule ids and counts only, never
/// paths or fingerprints.
#[test]
#[ignore]
fn audits_the_real_ssh_directory_without_panicking() {
    let Some(home) = dirs::home_dir() else {
        eprintln!("no home directory; skipping");
        return;
    };

    let dir = home.join(".ssh");
    if !dir.is_dir() {
        eprintln!("no ~/.ssh; skipping");
        return;
    }

    let report = audit::run(&dir, &HashSet::new()).expect("audit runs on a real directory");

    eprintln!(
        "keys={} score={} critical={} high={} medium={} low={} info={}",
        report.key_count,
        report.score,
        report.counts.critical,
        report.counts.high,
        report.counts.medium,
        report.counts.low,
        report.counts.info,
    );
    for finding in &report.findings {
        eprintln!("  {} [{:?}]", finding.rule_id, finding.severity);
    }

    // The score is derived from the findings, so an out-of-range value means
    // the weighting broke.
    assert!(report.score <= 100);
}

// ------------------------------------------------------ public key pairing

/// A different real key, so a mismatched `.pub` can be tested.
const OTHER_ED25519_PUB: &str = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl other@parolassh.invalid\n";

#[test]
fn a_matching_public_key_is_not_flagged() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    write(&dir.join("id_ed25519.pub"), ED25519_PUB);
    #[cfg(unix)]
    {
        chmod(dir, 0o700);
        chmod(&dir.join("id_ed25519"), 0o600);
    }

    let report = run(dir);
    let found = rules(&report);

    assert!(!found.contains(&"key.pub-mismatch"), "{found:?}");
    assert!(!found.contains(&"key.no-public"));
    assert!(!found.contains(&"key.pub-unreadable"));
}

#[test]
fn a_public_key_from_a_different_pair_is_flagged() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    // The classic breakage: the sidecar was regenerated or copied from
    // somewhere else, so anything deployed from it will never authenticate.
    write(&dir.join("id_ed25519"), ED25519_KEY);
    write(&dir.join("id_ed25519.pub"), OTHER_ED25519_PUB);
    #[cfg(unix)]
    {
        chmod(dir, 0o700);
        chmod(&dir.join("id_ed25519"), 0o600);
    }

    let report = run(dir);

    assert_eq!(
        severity_of(&report, "key.pub-mismatch"),
        Some(Severity::High)
    );

    // Both fingerprints belong in the message — that is what makes it
    // actionable rather than just alarming.
    let finding = report
        .findings
        .iter()
        .find(|finding| finding.rule_id == "key.pub-mismatch")
        .unwrap();
    assert!(finding.detail.contains("SHA256:"));
}

#[test]
fn a_corrupt_public_key_is_reported_separately() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    write(&dir.join("id_ed25519.pub"), "this is not a public key\n");

    let report = run(dir);
    let found = rules(&report);

    assert!(found.contains(&"key.pub-unreadable"));
    // Unreadable is not the same as mismatched; only one should fire.
    assert!(!found.contains(&"key.pub-mismatch"));
}

#[test]
fn a_missing_public_key_stays_informational() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);

    let report = run(dir);
    assert_eq!(severity_of(&report, "key.no-public"), Some(Severity::Info));
    assert!(!rules(&report).contains(&"key.pub-mismatch"));
}

#[test]
fn an_unparseable_private_key_does_not_claim_a_mismatch() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    // A legacy PEM cannot be decoded, so the sidecar cannot be checked —
    // reporting a mismatch here would be a guess, not a finding.
    write(&dir.join("id_rsa"), LEGACY_PEM_KEY);
    write(&dir.join("id_rsa.pub"), ED25519_PUB);

    let report = run(dir);
    let found = rules(&report);

    assert!(!found.contains(&"key.pub-mismatch"), "{found:?}");
    assert!(!found.contains(&"key.pub-unreadable"));
}

#[test]
fn a_generated_pair_always_matches() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    generate::generate(
        dir,
        GenerateRequest {
            algorithm: "ed25519".into(),
            bits: None,
            file_name: "id_ed25519".into(),
            comment: Some("me@laptop".into()),
            // Encrypted, because that path rebuilds the public half and is
            // where a mismatch would most plausibly creep in.
            passphrase: Some("hunter2".into()),
            overwrite: false,
        },
    )
    .unwrap();

    let report = run(dir);
    assert!(!rules(&report).contains(&"key.pub-mismatch"));
}

// ------------------------------------------------------------------ delete

#[test]
fn deleting_a_key_removes_both_halves() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    write(&dir.join("id_ed25519.pub"), ED25519_PUB);

    let removed = keys::delete(&dir.join("id_ed25519"), true).unwrap();

    assert_eq!(removed.len(), 2);
    assert!(!dir.join("id_ed25519").exists());
    assert!(!dir.join("id_ed25519.pub").exists());
}

#[test]
fn the_public_half_can_be_kept() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    write(&dir.join("id_ed25519.pub"), ED25519_PUB);

    let removed = keys::delete(&dir.join("id_ed25519"), false).unwrap();

    assert_eq!(removed.len(), 1);
    assert!(!dir.join("id_ed25519").exists());
    assert!(dir.join("id_ed25519.pub").exists());
}

#[test]
fn delete_refuses_anything_that_is_not_a_private_key() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    // A tampered path must not turn delete into a way to remove config or
    // known_hosts.
    write(&dir.join("config"), "Host a\n  User me\n");
    write(&dir.join("known_hosts"), KNOWN_HOSTS);
    write(&dir.join("id_ed25519.pub"), ED25519_PUB);

    for name in ["config", "known_hosts", "id_ed25519.pub"] {
        let error = keys::delete(&dir.join(name), true).unwrap_err();
        assert!(
            error.to_string().contains("not an SSH private key"),
            "{name}: {error}"
        );
        assert!(dir.join(name).exists(), "{name} must survive");
    }
}

#[test]
fn deleting_a_key_clears_its_findings() {
    let temp = tempfile::tempdir().unwrap();
    let dir = temp.path();

    write(&dir.join("id_ed25519"), ED25519_KEY);
    #[cfg(unix)]
    {
        chmod(dir, 0o700);
        chmod(&dir.join("id_ed25519"), 0o600);
    }

    assert!(rules(&run(dir)).contains(&"key.unencrypted"));

    keys::delete(&dir.join("id_ed25519"), true).unwrap();

    let after = run(dir);
    assert_eq!(after.key_count, 0);
    assert!(after.findings.is_empty());
}
